language: android
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+